### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [cafehaine/de_showcase#12]
Hi all.

I would like to help with some research, according to my research there are at least 30+- types of desktop environment in Linux today. I would like to add a screenshot and description of each type of desktop environment here so that people have this information publicly when choosing a distro. 

I've recently been working on distrochooser. And this repository is very interesting and I want to help as I can. Per example, 

> All desktop environments I researched:
|> XFCE4
|> GNOME
|> snakeware desktop
|> SharpEnviro
|> eXtern-OS(eXtern-OS)
|> Durden(desktop environment for the [Arcan](https://www.arcan-fe.com/) Display Server)
|> Regolith Desktop Environment
|> jappeOsDesktop
|> CutefishOS
|> VIM-OS(Desktop environment based on VIM only)
|> NightOS(Desktop environment NightOS)
|> UKUI
|> Draco Desktop Environment
|> Budgie
|> fynedesk(desktop environment for fynedesk-os)
|> Nadva(official desktop environment AvdanOS)
|> lumina
|> jde(some desktop environment in manjaro)
|> Cosmic(popOS)
|> NeXTSTEP
|> KDE
|> XFCE 
|> Sugar
|> MATE
|> Desktop environment for Wayland
|> MoonLightDE
|> mapeo-desktop
|> Desktop Environment for Arcan
|> daedalOS
|> Jade
|> LXDE 
|> Unity
|> Phosh core
|> Abanu(Desktop Environment for Windows and Linux)
|> Pantheon 
|> GNOME Flashback
|> TOS Desktop Environment
|> Trinity Desktop Environment
|> Laniakea Desktop Environment
|> Enlightenment 
|> Deepin
|> LXQT
|> Cinnamon
|> AtomOS Desktop Environment
...

> All window managers I researched:
|> i3
|> sway
|> Awesome WM 
|> DWM
|> Xmonad
|> ibis
|> bspwm
|> XtermWM
|> [9wm](https://en.wikipedia.org/wiki/9wm)
|> dynamic desktop environment
|> IceWM
|> Spectrwm 
|> Openbox
|> Fluxbox
|> herbstluftwm
...

**Comment by cafehaine** [comment]
You're welcome to contribute to this project if you want to :)

**Comment by ghost** [comment]
Hi cafehaine.

> You're welcome to contribute to this project if you want to :)

thank you for feedback. So... I will close this issue, you clarified my doubt.

*Have a great day, and thank you for your patience in answering my question.*
