### ISSUE TITLE
add CodeOfConduct.md in de_showcase?

### ISSUE THREAD

**Issue by codehangen** [cafehaine/de_showcase#16]
Hi all.

I wonder if you've all thought about adding the file: CodeOfConduct in the README.md. *Have you thought about adding the file: CodeOfConduct.md in de_showcase?*

#### What is CodeOfConduct?
A code of conduct is a set of values, rules, standards, and principles outlining what employers expect from staff within an organization.

**Comment by cafehaine** [comment]
I haven't really thought about it since I was the only one contributing to this repository, but I wouldn't mind adding one.

Do you happen to know existing COCs that would be a good fit?

**Comment by cafehaine** [comment]
Done in 6cdd12a0aa8f4be2837e1764d377445b5052ecb0 :)
