### ISSUE TITLE
new paths to de_showcase?

### ISSUE THREAD

**Issue by ghost** [cafehaine/de_showcase#22]
Hi all.

> I've built this since those UIs tend to change regularly, but I'm too lazy to create VMs to try those out regularly, so creating screenshots of the desktop is a good compromise in my opinion.

**use case 1(de_showcase cdn/web-app):** If there is a cdn network it is possible to share screen configurations. 

#### 1.1 idea 1: "cdn.de-showcase.net"
```html
<script src="https://cdn.de-showcase.net/ubuntu/gnome-version@2.0.1/gnome-ui.sh"></script>
```
- problem: Someone can send a malicious script. So it is necessary to check the received and sent files.
- partial solution: As it is a cdn network anyone can audit the code, malicious scripts can be removed by anyone by reporting the link

#### 1.2 idea 2: "de-showcase in IPFS"
Would be a site to send linux desktop environment screenshots. *So... I'm thinking of creating a site to de_showcase in ipfs. Thus, anyone can view this site and send the screen corresponding to the desktop to the community. In addition to configuring this desktop environment or sharing the configuration of this desktop environment on the de_showcase.*
- problem: It would be necessary to configure a site with IPFS
- problem 2: Someone can send a malicious script (in IPFS). So it is necessary to check the received and sent files.
- partial solution for problem 2: As it is a cdn network anyone can audit the code, malicious scripts can be removed by anyone by reporting the link

> I've built this since those UIs tend to change regularly, but I'm too lazy to create VMs to try those out regularly, so creating screenshots of the desktop is a good compromise in my opinion.

**use case 2 (de_showcase+osboxes):** Another possibility I was thinking about would be to use the [osboxes](https://www.osboxes.org/) service to have preview configurations for different desktop environments or graphical interfaces. It would only be necessary to run the pre-assembled script on the machine with the corresponding UI. We can create an internal service in virtualbox that communicates with a server and sends the corresponding screenshot. 
- problem: Anyone downloads the test image and when testing a script sends a preview image of the screenshoot. *So.. Someone could create custom isos with viruses to infect machines, domestiocs users using these machines with site login data could be tricked*
- partial solution: this can be resolved by telling users to only download official sources. For example: ``osboxes.org/de_showcase/gnome`` or ``osboxes.org/de_showcase/XFCE4``

> I've built this since those UIs tend to change regularly, but I'm too lazy to create VMs to try those out regularly, so creating screenshots of the desktop is a good compromise in my opinion.

**use case 3(bittorrent + de_showcase):** We can use bittorrent (protocol) to share desktop environment UI. Any user who uses gnome etc must inform the corresponding official tracker-torrent of the distro or community in the torrent file, so we can validate which screenshots are official and who made the corresponding screenshot. In this sense, we can index the official trackers of the distro or linux community with the corresponding ui

> I've built this since those UIs tend to change regularly, but I'm too lazy to create VMs to try those out regularly, so creating screenshots of the desktop is a good compromise in my opinion.

**use case 4:** Instead of having installation scripts, ask users to submit screenshots in this official repository.

> I've built this since those UIs tend to change regularly, but I'm too lazy to create VMs to try those out regularly, so creating screenshots of the desktop is a good compromise in my opinion.

**use case 5:** Use the app [UTM](https://github.com/utmapp/UTM) to generate screenshots of desktop environments with linux isos.

**Comment by cafehaine** [comment]
I think the current concept of using a script to generate all the configs automatically is ultimately the best way for what I want to achieve: View the most up to date default configurations.

I could configure github actions to automatically generate the screenshots using the scripts and serve them in artifacts, but that would require me to write some github action scripts which I'm really not used to (I usually use gitlab).

Ultimately, if people want to share their desktop screenshots the best place would be a place such as [r/unixporn](https://reddit.com/r/unixporn), but not this project which has for goal to show the default configurations.

**Comment by ghost** [comment]
Hi cafehaine.

> I think the current concept of using a script to generate all the configs automatically is ultimately the best way for what I want to achieve: View the most up to date default configurations.
> I could configure github actions to automatically generate the screenshots using the scripts and serve them in artifacts, but that would require me to write some github action scripts which I'm really not used to (I usually use gitlab).
> Ultimately, if people want to share their desktop screenshots the best place would be a place such as [r/unixporn](https://reddit.com/r/unixporn), but not this project which has for goal to show the default configurations.

thank you for feedback. I will close this issue, you clarified my doubt.

*Have a great day, and thank you for your patience in answering my question.*
